version: 2
updates:
  # Root directory - npm packages
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "develop"
    reviewers:
      - "bkimminich"
    labels:
      - "dependencies"
    ignore:
      - dependency-name: "express-jwt"
        versions: ["0.1.3"]
      - dependency-name: "sanitize-html"
        versions: ["1.4.2"]
      - dependency-name: "unzipper"
        versions: ["0.9.15"]
      - dependency-name: "jsonwebtoken"
        versions: ["0.4.0"]

  # Frontend directory - npm packages
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "daily"
    target-branch: "develop"
    reviewers:
      - "bkimminich"
    labels:
      - "dependencies"
